name: .NET CD - Pack and Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pack-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Setup .NET SDK(s)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.x
            9.x
      
      - name: Restore Dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore --configuration Release
      
      - name: Pack NuGet Package
        run: |
          dotnet pack ./src/SimpleResult/SimpleResult.csproj \
            --no-build \
            --configuration Release \
            -o ./artifacts \
            /p:PackageVersion=${{ steps.get_version.outputs.version }}

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate